#!/usr/bin/env python3
"""Reads /out/config.yml + the project tree mounted at /project (read-only),
and writes /out/docker-compose.yml. See cc-docker README for the config schema.
"""
import os
import sys
from pathlib import Path, PurePosixPath

import yaml

CONTAINER_PROJECT_ROOT = Path("/project")
CONFIG_PATH = Path("/out/config.yml")
OUTPUT_PATH = Path("/out/docker-compose.yml")

HEADER = (
    "# Generated by cc-config from .cc-docker/config.yml — DO NOT EDIT.\n"
    "# Edit .cc-docker/config.yml instead and regenerate (the `cc` launcher does this).\n"
)


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print(f"warning: {msg}", file=sys.stderr)


def load_config():
    if not CONFIG_PATH.is_file():
        die(f"{CONFIG_PATH} not found")
    with CONFIG_PATH.open() as f:
        config = yaml.safe_load(f) or {}
    if "image" not in config:
        die("config.yml missing required top-level key 'image'")
    return config


def depth(target):
    return len(PurePosixPath(target).parts)


def expand_excludes(entry_path_rel, container_path, host_path, excludes):
    """Yield (target_host_path, is_dir) for each path matched by an exclude glob."""
    for pattern in excludes:
        matches = sorted(container_path.glob(pattern))
        if not matches:
            warn(
                f"exclude '{pattern}' under mount '{entry_path_rel}' matched no files — skipping"
            )
            continue
        for match in matches:
            rel = match.relative_to(container_path)
            yield host_path / rel, match.is_dir()


def build_mount_volumes(mounts_cfg, project_dir, readonly):
    volumes = []
    root_covered = False
    project_dir_norm = os.path.normpath(project_dir)

    for entry in mounts_cfg:
        rel_path = entry.get("path")
        if rel_path is None:
            die("a 'mounts' entry is missing required key 'path'")

        container_path = (CONTAINER_PROJECT_ROOT / rel_path).resolve() if rel_path != "." \
            else CONTAINER_PROJECT_ROOT
        if not container_path.exists():
            die(f"mount path '{rel_path}' does not exist in the project")

        host_path = project_dir if rel_path == "." else os.path.normpath(
            os.path.join(project_dir, rel_path)
        )
        host_path = Path(host_path)

        if os.path.normpath(str(host_path)) == project_dir_norm:
            root_covered = True

        volumes.append(
            {
                "type": "bind",
                "source": str(host_path),
                "target": str(host_path),
                "read_only": bool(readonly),
            }
        )

        for target, is_dir in expand_excludes(
            rel_path, container_path, host_path, entry.get("exclude", [])
        ):
            if is_dir:
                volumes.append({"type": "tmpfs", "target": str(target)})
            else:
                volumes.append(
                    {
                        "type": "bind",
                        "source": "/dev/null",
                        "target": str(target),
                        "read_only": True,
                    }
                )

    volumes.sort(key=lambda v: depth(v["target"]))
    return volumes, root_covered


def main():
    project_dir = os.environ.get("PROJECT_DIR")
    if not project_dir:
        die("PROJECT_DIR environment variable is not set")
    project_dir = os.path.normpath(project_dir)

    config = load_config()
    image = config["image"]
    git_cfg = config.get("git", {})
    env_cfg = config.get("env", {})
    readonly = config.get("readonly", False)
    mounts_cfg = config.get("mounts", [])
    extra_mounts_cfg = config.get("extra_mounts", [])

    volumes, root_covered = build_mount_volumes(mounts_cfg, project_dir, readonly)

    # Always-available mounts. ~ is left unexpanded so docker compose expands
    # it against the invoking host user's home, matching today's behavior.
    volumes.append({"type": "bind", "source": "~/.claude", "target": "/home/hostuser/.claude"})
    volumes.append(
        {
            "type": "bind",
            "source": "~/.claude.json",
            "target": "/home/hostuser/.claude.json",
        }
    )
    if not root_covered:
        config_yml_path = str(Path(project_dir) / ".cc-docker" / "config.yml")
        volumes.append(
            {
                "type": "bind",
                "source": config_yml_path,
                "target": config_yml_path,
                "read_only": True,
            }
        )

    for extra in extra_mounts_cfg:
        volumes.append(extra)

    environment = {}
    if git_cfg.get("name"):
        environment["GIT_USER_NAME"] = git_cfg["name"]
    if git_cfg.get("email"):
        environment["GIT_USER_EMAIL"] = git_cfg["email"]
    environment["PROJECT_DIR"] = project_dir
    environment.update(env_cfg)

    compose = {
        "services": {
            "cc": {
                "image": image,
                "hostname": "cc",
                "stdin_open": True,
                "tty": True,
                "working_dir": project_dir,
                "environment": environment,
                "volumes": volumes,
            }
        }
    }

    OUTPUT_PATH.write_text(HEADER + yaml.dump(compose, sort_keys=False, default_flow_style=False))
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
