#!/usr/bin/env python3
"""Reads /out/cc-docker.yml + the project tree mounted at /project (read-only),
and writes /out/docker-compose.yml. See the README section "Configuring cc-docker"
for the config schema (also available machine-readable as cc-docker.schema.json).
"""
import json
import os
import re
import sys
from pathlib import Path, PurePosixPath

import jsonschema
import yaml

CONTAINER_PROJECT_ROOT = Path("/project")
CONFIG_PATH = Path("/out/cc-docker.yml")
OUTPUT_PATH = Path("/out/docker-compose.yml")
# Sidecars for the host launcher (modular mode): the assembled image tag and the raw
# module-name list. Presence of assembled.tag is how the launcher detects modular vs
# legacy mode, so legacy runs clear them.
TAG_SIDECAR = Path("/out/assembled.tag")
MODULES_SIDECAR = Path("/out/assembled.modules")

CLAUDE_DIR = "/home/hostuser/.claude"

# Container-side view of the host's $PROJECT_DIR/.cc-docker/.claude bind source
# (see the overlay mount below) — /out is that project's .cc-docker/, mounted r/w.
OVERLAY_DIR = Path("/out/.claude")
# Resolved relative to this script so it works both inside the cc-config image
# (script + schema both copied to /) and when run directly from the repo
# checkout (script + schema both live in toolchain/config/).
SCHEMA_PATH = Path(__file__).resolve().parent / "cc-docker.schema.json"

HEADER = (
    "# Generated by cc-config from .cc-docker/cc-docker.yml — DO NOT EDIT.\n"
    "# Edit .cc-docker/cc-docker.yml instead and regenerate (the `cc` launcher does this).\n"
)


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print(f"warning: {msg}", file=sys.stderr)


def validate_config(config):
    schema = json.loads(SCHEMA_PATH.read_text())
    validator = jsonschema.Draft7Validator(schema)
    errors = sorted(validator.iter_errors(config), key=lambda e: list(e.path))
    if not errors:
        return
    for error in errors:
        location = "/".join(str(p) for p in error.path) or "<root>"
        warn(f"cc-docker.yml: {location}: {error.message}")
    die("cc-docker.yml failed schema validation")


def load_config():
    if not CONFIG_PATH.is_file():
        die(f"{CONFIG_PATH} not found")
    with CONFIG_PATH.open() as f:
        config = yaml.safe_load(f) or {}
    validate_config(config)
    return config


def depth(target):
    return len(PurePosixPath(target).parts)


def expand_excludes(entry_path_rel, container_path, host_path, excludes):
    """Yield (target_host_path, is_dir) for each path matched by an exclude glob."""
    for pattern in excludes:
        matches = sorted(container_path.glob(pattern))
        if not matches:
            warn(
                f"exclude '{pattern}' under mount '{entry_path_rel}' matched no files — skipping"
            )
            continue
        for match in matches:
            rel = match.relative_to(container_path)
            yield host_path / rel, match.is_dir()


def build_mount_volumes(mounts_cfg, project_dir, readonly):
    volumes = []
    root_covered = False
    project_dir_norm = os.path.normpath(project_dir)

    for entry in mounts_cfg:
        rel_path = entry["path"]

        # Constrain the mount to the project. `path` flows into both a container
        # path (CONTAINER_PROJECT_ROOT / rel_path) and a host path
        # (os.path.join(project_dir, rel_path)); on an absolute or `..`-bearing
        # value both the `/` operator and os.path.join drop the project prefix and
        # escape — e.g. `/etc` or `../../..` would bind the host's /etc or / at its
        # own path, read-write (security-audit.md #4). Reject anything that doesn't
        # stay inside the project. The schema also blocks these (a `path` pattern),
        # so this is defense in depth for a hand-edited or schema-bypassed config.
        if os.path.isabs(rel_path):
            die(f"mount path '{rel_path}' must be relative to the project root")

        if rel_path == ".":
            container_path = CONTAINER_PROJECT_ROOT
        else:
            container_path = (CONTAINER_PROJECT_ROOT / rel_path).resolve()
            # .resolve() follows symlinks; since /project mirrors the host project
            # tree, this also catches a repo symlink that points outside the project.
            if not container_path.is_relative_to(CONTAINER_PROJECT_ROOT):
                die(f"mount path '{rel_path}' escapes the project root")
        if not container_path.exists():
            die(f"mount path '{rel_path}' does not exist in the project")

        host_path = project_dir if rel_path == "." else os.path.normpath(
            os.path.join(project_dir, rel_path)
        )
        # Defense in depth: the host path that is actually bind-mounted must also
        # stay within the project (guards the string-join path independently of the
        # container-side resolve check above).
        host_path_norm = os.path.normpath(str(host_path))
        if host_path_norm != project_dir_norm \
                and not host_path_norm.startswith(project_dir_norm + os.sep):
            die(f"mount path '{rel_path}' escapes the project root")
        host_path = Path(host_path)

        if host_path_norm == project_dir_norm:
            root_covered = True

        volumes.append(
            {
                "type": "bind",
                "source": str(host_path),
                "target": str(host_path),
                "read_only": bool(readonly),
            }
        )

        for target, is_dir in expand_excludes(
            rel_path, container_path, host_path, entry.get("exclude", [])
        ):
            if is_dir:
                volumes.append({"type": "tmpfs", "target": str(target)})
            else:
                volumes.append(
                    {
                        "type": "bind",
                        "source": "/dev/null",
                        "target": str(target),
                        "read_only": True,
                    }
                )

    volumes.sort(key=lambda v: depth(v["target"]))
    return volumes, root_covered


def resolve_api_key_file(path):
    """Resolve `anthropic_api_key_file` to an absolute host path. A leading ~ or
    ~/ is expanded against CC_HOST_HOME — the `cc` launcher's own home, forwarded
    in because this container has no other way to see it (same pattern as the
    CC_HOST_* display vars). Emitting an absolute path here avoids depending on
    docker compose's own (unverified) ~-expansion for `secrets.*.file`.
    """
    if path == "~" or path.startswith("~/"):
        host_home = os.environ.get("CC_HOST_HOME")
        if not host_home:
            die(
                "anthropic_api_key_file uses '~' but CC_HOST_HOME is not set — "
                "run via the `cc` launcher, not cc-config directly, or use an "
                "absolute path instead"
            )
        path = host_home + path[1:]
    return os.path.normpath(path)


def apply_display(config, environment, volumes):
    """Forward the host's clipboard display socket into the container, so
    `claude` can paste images from the host clipboard. The `cc` launcher runs
    with a real host shell environment and forwards a snapshot of it here as
    CC_HOST_* — this container (cc-config) has no other way to see it. Those
    CC_HOST_* vars are only used to *detect* which display server is active;
    the values written into the compose file are ${VAR}-style references so
    `docker compose run` resolves them fresh from the host shell's own
    environment every time, instead of baking in a value that could go stale.

    X11 is forwarded only on an *explicit* `display: x11`, never from `auto`.
    X11 has no inter-client isolation, so a forwarded (trusted) cookie lets the
    container keylog the session, capture any window, and inject synthetic
    keystrokes into host windows via XTEST — i.e. host RCE (security-audit.md
    #5). Wayland isolates clients and has no global input capture, so `auto`
    forwards it freely; on an X11-only host `auto` skips forwarding and points
    the user at the explicit opt-in.
    """
    mode = config.get("display", "auto")
    if mode == "disabled":
        return

    auto = mode == "auto"
    if auto:
        if os.environ.get("CC_HOST_WAYLAND_DISPLAY"):
            mode = "wayland"
        elif os.environ.get("CC_HOST_DISPLAY"):
            mode = "x11"
        else:
            warn(
                "display: auto found no host display server (run via the `cc` "
                "launcher, not cc-config directly, for auto-detection) — "
                "skipping clipboard forwarding"
            )
            return

    if mode == "wayland":
        environment.setdefault("WAYLAND_DISPLAY", "${WAYLAND_DISPLAY}")
        environment.setdefault("XDG_RUNTIME_DIR", "${XDG_RUNTIME_DIR}")
        volumes.append("${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}")
    elif mode == "x11":
        if auto:
            # auto never forwards trusted X11 (no client isolation → keylogging +
            # XTEST keystroke injection into host windows = host RCE;
            # security-audit.md #5). Require an explicit `display: x11` opt-in.
            warn(
                "display: auto detected an X11 host and will NOT forward it: X11 "
                "has no client isolation, so the container would gain full input "
                "access to your session (keylogging, synthetic keystrokes into "
                "host windows). Set 'display: x11' explicitly to enable it anyway, "
                "or use Wayland."
            )
            return
        # Explicit display: x11 — informed opt-in to the trusted-cookie risk. The
        # compose writes ${XAUTHORITY} for `docker compose run` to resolve; if the
        # host shell has no XAUTHORITY there's no cookie to forward (and the naive
        # mount would be the malformed ':/home/hostuser/.Xauthority:ro'), so skip.
        if not os.environ.get("CC_HOST_XAUTHORITY"):
            warn(
                "display: x11 needs XAUTHORITY set on the host (the X cookie to "
                "forward) but it is unset — skipping X11 forwarding."
            )
            return
        warn(
            "display: x11 forwards a TRUSTED X cookie — the container can keylog "
            "your session and inject keystrokes into host windows. Use it only "
            "for a project you trust with that access."
        )
        environment.setdefault("DISPLAY", "${DISPLAY}")
        environment.setdefault("XAUTHORITY", "/home/hostuser/.Xauthority")
        volumes.append("/tmp/.X11-unix:/tmp/.X11-unix")
        volumes.append("${XAUTHORITY}:/home/hostuser/.Xauthority:ro")


def apply_docker_socket(config, volumes):
    """Mount the host's Docker socket in, if opted into via `docker_socket:
    true`. This grants root-equivalent access to the host daemon — see the
    schema description. cc-wrapper.sh (bootstrap/) grants the in-container
    hostuser access to the mounted socket at container start, since it's
    root-owned on the host.
    """
    if not config.get("docker_socket", False):
        return
    volumes.append(
        {
            "type": "bind",
            "source": "/var/run/docker.sock",
            "target": "/var/run/docker.sock",
        }
    )


def main():
    project_dir = os.environ.get("PROJECT_DIR")
    if not project_dir:
        die("PROJECT_DIR environment variable is not set")
    project_dir = os.path.normpath(project_dir)

    config = load_config()
    modules = config.get("modules")
    if modules is not None:
        # Modular mode: the image is the deterministic assembled tag. cc-config is the
        # SOLE tag computer — Python sorted() is the canonical sort; the launcher reads
        # the tag back from the sidecar and never recomputes it.
        image = "cc/" + ("-".join(sorted(modules)) if modules else "base")
    else:
        image = config["image"]
    git_cfg = config.get("git", {})
    env_cfg = config.get("env", {})
    readonly = config.get("readonly", False)
    mounts_cfg = config.get("mounts", [])
    extra_mounts_cfg = config.get("extra_mounts", [])
    api_key_file = config.get("anthropic_api_key_file")
    if api_key_file:
        api_key_file = resolve_api_key_file(api_key_file)

    volumes, root_covered = build_mount_volumes(mounts_cfg, project_dir, readonly)

    # ~/.claude is a dedicated per-project Docker named volume, fully decoupled from
    # the host's ~/.claude — nothing on the host filesystem is involved. This is a
    # net security improvement over the old read-only-host-bind + tmpfs-allowlist:
    #
    #   * #1 (host RCE) is eliminated structurally: the volume is never read by the
    #     *host* claude, so hooks / commands/ / settings.json a compromised agent
    #     writes only ever execute inside the sandbox it already controls. That is
    #     why the whole tree can now be read-write — the read-only base existed only
    #     to stop writes reaching a host-executed path, which no longer exists.
    #   * #2 (cross-project leak) is eliminated: the volume is per-project (keyed on
    #     the slug below), so no other project's transcripts / history / MCP configs
    #     are reachable. This also closes the deferred ~/.claude.json residual — see
    #     CLAUDE_CONFIG_DIR below.
    #   * Residual: intra-project persistence (an agent can plant a hook that fires
    #     on THIS project's next run), which never crosses out of a sandbox the agent
    #     already controls. See docs/security-audit.md.
    #
    # Setting CLAUDE_CONFIG_DIR to the mountpoint pulls ALL of Claude Code's state —
    # settings.json, .credentials.json, projects/ (transcripts + memory), and
    # .claude.json — inside this one volume. (.claude.json defaults to $HOME outside
    # the mount; CLAUDE_CONFIG_DIR relocates it to $CLAUDE_CONFIG_DIR/.claude.json.)
    # Transcripts/memory therefore persist per-project across runs automatically
    # (named volumes survive `docker compose run --rm`), so no host projects/<slug>
    # bind or pre-creation is needed anymore.
    slug = re.sub(r"[^a-zA-Z0-9]", "-", project_dir)
    claude_volume = f"cc-claude-{slug}"
    volumes.append(
        {"type": "volume", "source": claude_volume, "target": CLAUDE_DIR}
    )
    # Auth: with anthropic_api_key_file the key arrives as a Docker secret (below)
    # and never touches the volume. Without it, the agent uses OAuth — a fresh
    # volume simply prompts an interactive `claude` login on first run, and the
    # token then persists inside the volume. Either way there is no host credential
    # bind, so the old null-mask login-success-then-fail loop cannot occur.

    # Redirect the project-level .claude/ execution context into the gitignored
    # .cc-docker/.claude/ (scaffolded here). This overlays $PROJECT_DIR/.claude,
    # so Claude's project-level writes (settings.local.json, plans/, todos) never
    # land in the committed/shared project tree.
    OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
    overlay_settings = OVERLAY_DIR / "settings.json"
    if not overlay_settings.exists():
        overlay_settings.write_text("{}\n")
    volumes.append(
        {
            "type": "bind",
            "source": str(Path(project_dir) / ".cc-docker" / ".claude"),
            "target": str(Path(project_dir) / ".claude"),
            "read_only": False,
        }
    )
    # The config that defines the NEXT session's sandbox lives in .cc-docker/
    # (cc-docker.yml, the generated docker-compose.yml, and the launcher sidecars).
    # It sits at the project root, so the default `path: .` mount makes the whole
    # directory read-write — a compromised agent could rewrite cc-docker.yml to
    # pre-authorize its own escape on the next run (extra_mounts, docker_socket,
    # permission_mode: bypassPermissions, env injection; security-audit.md #3).
    # Layer a read-only bind over it (a ro bind on an rw parent is a VFS overlay,
    # not a write to the parent). Only needed when the project root is mounted —
    # otherwise .cc-docker isn't in the container at all. The .claude overlay below
    # is unaffected: it binds host .cc-docker/.claude to a DIFFERENT container
    # target ($PROJECT_DIR/.claude), and the generated files are written host-side
    # by cc-config before this container ever starts, so read-only here is correct.
    if root_covered:
        cc_docker_dir = str(Path(project_dir) / ".cc-docker")
        volumes.append(
            {
                "type": "bind",
                "source": cc_docker_dir,
                "target": cc_docker_dir,
                "read_only": True,
            }
        )

    for extra in extra_mounts_cfg:
        volumes.append(extra)

    environment = {}
    if git_cfg.get("name"):
        environment["GIT_USER_NAME"] = git_cfg["name"]
    if git_cfg.get("email"):
        environment["GIT_USER_EMAIL"] = git_cfg["email"]
    environment["PROJECT_DIR"] = project_dir
    # Point Claude Code's whole config dir at the per-project volume mounted at
    # CLAUDE_DIR, so .claude.json (which otherwise lives at $HOME, outside the
    # mount) and every other config/state file land inside the volume.
    environment["CLAUDE_CONFIG_DIR"] = CLAUDE_DIR
    # Forward the invoking host user's ids so cc-wrapper.sh can create `hostuser`
    # without stat-ing a mount. The ~/.claude volume is root-owned on first mount,
    # so the old "stat the .claude bind to recover the host UID" fallback no longer
    # works; passing the ids explicitly is both robust and independent of mounts.
    host_uid_env = os.environ.get("HOST_UID")
    host_gid_env = os.environ.get("HOST_GID")
    if host_uid_env:
        environment["CC_HOST_UID"] = host_uid_env
    if host_gid_env:
        environment["CC_HOST_GID"] = host_gid_env
    if config.get("permission_mode"):
        environment["CC_PERMISSION_MODE"] = config["permission_mode"]
    environment.update(env_cfg)

    apply_display(config, environment, volumes)
    apply_docker_socket(config, volumes)

    service = {
        "image": image,
        "hostname": "cc",
        "stdin_open": True,
        "tty": True,
        "working_dir": project_dir,
        "environment": environment,
        "volumes": volumes,
        # The entrypoint chain never traps or forwards SIGTERM to `claude`,
        # so `docker stop`/`compose down` always ends in a SIGKILL anyway —
        # a nonzero grace period would just be dead waiting time.
        "stop_grace_period": "0s",
    }
    if api_key_file:
        # Delivered as a real Docker secret (a file under /run/secrets/, not an
        # env var) so the key never appears in `docker inspect`, this compose
        # file, or the container environment. run-as-hostuser.sh reads the file
        # and exports ANTHROPIC_API_KEY right before launching claude.
        service["secrets"] = ["anthropic_api_key"]

    compose = {"services": {"cc": service}}
    # Declare the per-project ~/.claude volume. The explicit `name:` pins the real
    # Docker volume name (otherwise compose prefixes it with the project name),
    # keeping it stable across runs; named volumes are not removed by `run --rm`.
    compose["volumes"] = {claude_volume: {"name": claude_volume}}
    if api_key_file:
        compose["secrets"] = {"anthropic_api_key": {"file": api_key_file}}

    OUTPUT_PATH.write_text(HEADER + yaml.dump(compose, sort_keys=False, default_flow_style=False))

    # cc-config runs as root, so anything it writes under /out is root-owned on
    # the host. Chown it all back to the invoking host user (the `cc` launcher
    # passes their ids as HOST_UID/HOST_GID) so it stays editable without sudo.
    host_uid = os.environ.get("HOST_UID")
    host_gid = os.environ.get("HOST_GID")
    if host_uid and host_gid:
        uid, gid = int(host_uid), int(host_gid)
        os.chown(OUTPUT_PATH, uid, gid)
        os.chown(OVERLAY_DIR, uid, gid)
        if overlay_settings.exists():
            os.chown(overlay_settings, uid, gid)

    # Launcher sidecars. In modular mode write the tag + module-name list (so the host
    # never re-parses cc-docker.yml or recomputes the tag); in legacy mode clear any
    # stale sidecars so "assembled.tag present → modular" stays a correct mode check.
    if modules is not None:
        TAG_SIDECAR.write_text(image + "\n")
        MODULES_SIDECAR.write_text("".join(m + "\n" for m in sorted(modules)))
        if host_uid and host_gid:
            os.chown(TAG_SIDECAR, uid, gid)
            os.chown(MODULES_SIDECAR, uid, gid)
    else:
        TAG_SIDECAR.unlink(missing_ok=True)
        MODULES_SIDECAR.unlink(missing_ok=True)

    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
