#!/usr/bin/env python3
"""cc-assemble — generate .cc-docker/assembled.Dockerfile from a modular cc-docker.yml.

Reads /out/cc-docker.yml (the project config, for its `modules:` list) and each
selected module's /stack/<name>/module.yml (the cc-docker repo's stack/ mounted
read-only), then emits the assembled Dockerfile the host launcher builds. Pure text
generation — no Docker, mirroring cc-config's containerized-generator design.

The final's band order: FROM base (band 1 + claude) → COPY --from stack modules
(band 2) → merged ENV → bootstrap scripts (band 4, baked leaf) → ENTRYPOINT.
The launcher builds it with context = $CC_DOCKER_DIR/bootstrap, so the bootstrap
COPYs are relative to that dir.
"""
import json
import os
import sys
from pathlib import Path

import jsonschema
import yaml

CONFIG_PATH = Path("/out/cc-docker.yml")
STACK_ROOT = Path("/stack")
OUTPUT_PATH = Path("/out/assembled.Dockerfile")
SCHEMA_PATH = Path(__file__).resolve().parent / "module.schema.json"

HEADER = (
    "# Generated by cc-assemble from .cc-docker/cc-docker.yml — DO NOT EDIT.\n"
    "# Regenerated on every `cc` launch. Build context: $CC_DOCKER_DIR/bootstrap.\n"
)


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print(f"warning: {msg}", file=sys.stderr)


def load_yaml(path):
    with path.open() as f:
        return yaml.safe_load(f) or {}


def load_module(name, validator):
    mod_file = STACK_ROOT / name / "module.yml"
    if not mod_file.is_file():
        die(f"module '{name}': {mod_file} not found (no such stack module)")
    mod = load_yaml(mod_file)
    errors = sorted(validator.iter_errors(mod), key=lambda e: list(e.path))
    if errors:
        for e in errors:
            loc = "/".join(str(p) for p in e.path) or "<root>"
            warn(f"module '{name}': {loc}: {e.message}")
        die(f"module '{name}': module.yml failed schema validation")
    if mod["name"] != name:
        die(f"module '{name}': module.yml declares name '{mod['name']}' (must match dir)")
    return mod


def main():
    config = load_yaml(CONFIG_PATH)
    modules = config.get("modules")
    if modules is None:
        die("cc-docker.yml has no `modules:` — cc-assemble runs only in modular mode")
    modules = sorted(modules)

    schema = json.loads(SCHEMA_PATH.read_text())
    validator = jsonschema.Draft7Validator(schema)
    mods = [load_module(name, validator) for name in modules]

    lines = ["FROM base"]

    # band 2 — COPY --from each module's artifacts, tagged with its version.
    for m in mods:
        tag = f"stack/{m['name']}:{m['version']}"
        for art in m["artifacts"]:
            lines.append(f"COPY --from={tag} {art} {art}")

    # merged env: one PATH line (prepend form, sorted-module order, deduped) plus one
    # ENV per non-PATH var; warn on conflicting non-PATH keys across modules.
    path_dirs = []
    other_env = {}
    for m in mods:
        for k, v in (m.get("env") or {}).items():
            if k == "PATH":
                prefix = v.split(":${PATH}")[0] if ":${PATH}" in v else v
                for d in prefix.split(":"):
                    if d and d not in path_dirs:
                        path_dirs.append(d)
            elif k in other_env and other_env[k] != v:
                warn(f"env key '{k}' set by multiple modules with different values; using '{v}'")
                other_env[k] = v
            else:
                other_env[k] = v
    if path_dirs:
        lines.append('ENV PATH="' + ":".join(path_dirs) + ':${PATH}"')
    for k in sorted(other_env):
        lines.append(f'ENV {k}="{other_env[k]}"')

    # band 4 — bootstrap (baked leaf). Context is $CC_DOCKER_DIR/bootstrap.
    lines += [
        "COPY cc-wrapper.sh /cc-wrapper.sh",
        "COPY run-as-hostuser.sh /run-as-hostuser.sh",
        "COPY sandbox.md /sandbox.md",
        "RUN chmod +x /cc-wrapper.sh /run-as-hostuser.sh",
        'ENTRYPOINT ["/cc-wrapper.sh"]',
    ]

    OUTPUT_PATH.write_text(HEADER + "\n".join(lines) + "\n")

    # Chown back to the invoking host user (root-created under /out otherwise).
    host_uid = os.environ.get("HOST_UID")
    host_gid = os.environ.get("HOST_GID")
    if host_uid and host_gid:
        os.chown(OUTPUT_PATH, int(host_uid), int(host_gid))

    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
